services:
  - type: web
    name: todo-hs-app
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: tododb
          property: connectionString

databases:
  - name: tododb
    databaseName: tododb
    user: render
